openapi: "3.0.0"
info:
  version: 1.0.0
  title: mixway API Documents
servers:
  - url: https://mixway.ekispert.jp
security:
  - ApiKeyAuth: []
category: "駅の情報"
paths:
  /v1/json/course/trainStation:
    get:
      tags:
        - 列車等の停車駅情報
      description: |-
        ### 概要
        経路シリアライズデータの経路もしくは区間から、通過する駅と停車する駅の一覧を取得します。<br>
        [駅すぱあとWebサービスの対応するAPI](http://docs.ekispert.com/v1/api/course/trainStation.html)<br>

        ### リクエストパラメータ
        <table class="comparison">
        <tr><th>パラメータ名</th><th>EWS</th><th>mixway</th><th>備考</th></tr>
        <tr><td>key</td><td>○</td><td>○</td><td></td></tr>
        <tr><td>serializeData</td><td>○</td><td>○</td><td>mixway形式経路シリアライズデータのみ利用可能</td></tr>
        <tr><td>checkEngineVersion</td><td>○</td><td>○</td><td>デフォルト値が異なる</td></tr>
        <tr><td>sectionIndex</td><td>○</td><td>○</td><td></td></tr>
        <tr><td>lineCode</td><td>○</td><td>○</td><td></td></tr>
        <tr><td>sectionOnly</td><td>○</td><td>○</td><td></td></tr>
        <tr><td>gcs</td><td>○</td><td>☓</td><td></td></tr>
        </table>
        <div class="about-comparison-table">
          ○＝パラメータあり　☓＝パラメータなし　両方○でも機能差異がある場合は備考欄および後述のParameters節に記載。
        </div>

        ### レスポンス
        本APIのレスポンス構造は駅すぱあとWebサービスの対応するAPI（JSON版）と完全に同一です。
      parameters:
        - name: serializeData
          description: |-
            **mixway形式経路シリアライズデータ**。駅すぱあとWebサービス形式経路シリアライズデータは利用できません。必須。
          in: query
          required: true
          schema:
            type: string
        - name: checkEngineVersion
          description: |-
            完全な定期経路シリアライズデータ、及びmixway形式経路シリアライズデータの再現を行う場合は、シリアライズデータ作成時のエンジンバージョンと再現時のエンジンバージョンが同一かのチェックを有効にします。エンジンバージョンが異なる場合は、エラーを返します。省略可。
            指定できる値: 
            - true: チェックする
            - false: チェックしない

            Default: `false`<br>
            `※ 駅すぱあとWebサービスとはデフォルト値が異なります。`
          in: query
          required: false
          schema:
            type: string
        - name: sectionIndex
          description: |-
            [区間インデックス](http://docs.ekispert.com/v1/dictionary/section-index/)。 省略可。省略時は経路全体を対象とします。
          in: query
          required: false
          schema:
            type: integer
        - name: lineCode
          description: |-
            [列車等を特定するコード](http://docs.ekispert.com/v1/dictionary/code-for-specifying-train/)の指定。必須
            詳しくは[こちら](http://docs.ekispert.com/v1/api/course/trainStation.html#linecode)を参照。
          in: query
          required: true
          schema:
            type: string
        - name: sectionOnly
          description: |-
            停車駅取得の範囲。省略可。<br>
            指定できる値:
            - true: 区間のみ
            - false: 全体

            Default: `true`<br>
            詳しくは[こちら](http://docs.ekispert.com/v1/api/course/trainStation.html#sectiononly)を参照。<br>
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: 正常レスポンスの場合
components:
  securitySchemes:
    ApiKeyAuth:        # arbitrary name for the security scheme
      type: apiKey
      in: query       # can be "header", "query" or "cookie"
      name: key  # name of the header, query parameter or cookie
  schemas:

