# This is a basic workflow to help you get started with Actions

name: StagingCI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: 
  push:
    branches:
      - '*'
      - '!master'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1
    - name: python version
      run: |
        python --version
    - name: easy_install install
      run: |
        sudo apt-get install python-setuptools
    - name: pip install
      run: |
        sudo apt-get install python-pip
    - name: create directory
      run: |
        mkdir ${GITHUB_REF##*/}
    - name: Copy ymls to html
      run: |
        python ./bin/cp_index.py dev
    - name: mv to branch_dir
      run: |
        mv index.html api ${GITHUB_REF##*/}
    - name: Copy files to S3 with the AWS CLI
      run: |
        aws s3 sync ${GITHUB_REF##*/} s3://fujitsu-upload/confidentials/${GITHUB_REF##*/}/
